import turtle

screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor("white")
t = turtle.Turtle()
t2 = turtle.Turtle()

pen = turtle.Turtle()

#intro screen
t.penup()
t.goto(0, 100)
t.pendown()
t.write("Welcome to",font=("arial",30,"italic"),align="center")

t.penup()
t.goto(0, 23)
t.pendown()
screen.addshape("welcome.gif")
t.shape("welcome.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(0, -100)
t.pendown()
t.write("Xavier's Presentation",font=("arial",30,"italic"),align="center")
t.penup()
t.goto(0,200)
t.pendown()
t.begin_fill()
t.fillcolor("purple")
t.circle(25)
t.end_fill()

round = input("Press Enter to Continue: ")
t.clear()
screen.screensize(500,500)
screen.bgcolor("purple")

t.penup()
t.goto(0, 200)
t.pendown()
t.write("My 3 favorite foods",font=("arial",30,"italic"),align="center")
t.penup()
t.goto(-50,-300)
t.pendown()
t.begin_fill()
t.fillcolor("blue")
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.end_fill()

t.penup()
t.goto(0, 0)
t.pendown()
screen.addshape("Untitled drawing.gif")
t.shape("Untitled drawing.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(0,110)
t.pendown()
t.write("Chicken Quesadilla",font=("arial",15,"italic"),align="center")

t.penup()
t.goto(250,0)
t.pendown()
screen.addshape("Untitled drawing2.gif")
t.shape("Untitled drawing2.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(230,100)
t.pendown()
t.write("Chicken and Rice",font=("arial",15,"italic"),align="center")

t.penup()
t.goto(-250,0)
t.pendown()
screen.addshape("Untitled drawing3.gif")
t.shape("Untitled drawing3.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(-250,100)
t.pendown()
t.write("Ceral",font=("arial",15,"italic"),align="center")

round = input("Press Enter to Continue: ")
t.clear()
screen.screensize(500,500)
screen.bgcolor("blue")

t.penup()
t.goto(0, 300)
t.pendown()
t.write("My 4 hobbies",font=("arial",30,"italic"),align="center")
t.penup()
t.goto(-50,-300)
t.pendown()
t.begin_fill()
t.fillcolor("orange")
def draw_rectangle(width, height):
    for _ in range(2):
        t.forward(width)
        t.left(90)
        t.forward(height)
        t.left(90)

draw_rectangle(100, 50)
t.end_fill()

t.penup()
t.goto(-150, 0)
t.pendown()
screen.addshape("Untitled drawing4.gif")
t.shape("Untitled drawing4.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(150, 0)
t.pendown()
screen.addshape("Untitled drawing5.gif")
t.shape("Untitled drawing5.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(-150, 150)
t.pendown()
screen.addshape("Untitled drawing6.gif")
t.shape("Untitled drawing6.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(150, 150)
t.pendown()
screen.addshape("Untitled drawing7.gif")
t.shape("Untitled drawing7.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(0, -225)
t.pendown()
t.write(" I like to hangout with friends I also like to go to amusement parks,\n another one of my hobbies is swimming but I like it more at the beach,\n and my last one is the gym I love hitting the gym. ,",font=("arial",15,"italic"),align="center")

round = input("Press Enter to Continue: ")
t.clear()
screen.screensize(500,500)
screen.bgcolor("orange")

t.penup()
t.goto(0, 200)
t.pendown()
t.write("My Favorite Movie is\n Good Will Hunting ",font=("arial",30,"italic"),align="center")


num_sides = 6
side_length = 100
angle = 360.0 / num_sides


pen.penup()
pen.goto(-50,-200)
pen.pendown()
pen.begin_fill()
pen.fillcolor("red")
for _ in range(num_sides):
    pen.forward(side_length)
    pen.right(angle)
pen.end_fill()

t.penup()
t.goto(0, 0)
t.pendown()
screen.addshape("Untitled drawing8.gif")
t.shape("Untitled drawing8.gif")
t.stamp()
t.shape("classic")

round = input("Press Enter to Continue: ")
t.clear()
pen.clear()
screen.screensize(500,500)
screen.bgcolor("red")

t.penup()
t.goto(0, 200)
t.pendown()
t.write("My Favorite Sport is\n     Football ",font=("arial",30,"italic"),align="center")

t.penup()
t.goto(0,-300)
t.pendown()
t.begin_fill()
t.fillcolor("pink")
t.forward(150)
t.left(120)
t.forward(150)
t.left(120)
t.forward(150)
t.left(120)
t.forward(150)
t.left(120)
t.end_fill()

t.penup()
t.goto(0, 0)
t.pendown()
screen.addshape("Untitled drawing9.gif")
t.shape("Untitled drawing9.gif")
t.stamp()
t.shape("classic")

t.penup()
t.goto(-20, -200)
t.pendown()
t.write("The End",font=("arial",30,"italic"),align="center")



turtle.done()